### ISSUE TITLE
Can't read the notebook on github

### ISSUE THREAD

**Issue by vhtnguyen** [ebrahimiae/Simplex-Algorithm#1]
It said "Invalid Notebook
Additional properties are not allowed ('metadata' was unexpected)
Using nbformat v5.8.0 and nbconvert v7.2.7"

**Comment by ebrahimiae** [comment]
Hi there, I checked it and upload the "Code file" again in the repository.
Thank you for your comment. :)

**Comment by vhtnguyen** [comment]
> 

It worked. Thanks for sharing :)
